name: Go Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      INFERABLE_API_SECRET: ${{ secrets.INFERABLE_API_SECRET }}
      INFERABLE_API_ENDPOINT: ${{ secrets.INFERABLE_API_ENDPOINT }}
      INFERABLE_CLUSTER_ID: ${{ secrets.INFERABLE_CLUSTER_ID }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22" # Use the Go version specified in your go.mod file

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
